;completa tu il programma 

; scrive 8 volte 255 in memoria a partire dalla   locazione di indirizzo 80 

        mov d,80

        mov c,8
; completa ....
; completa ....
; completa ....
; completa ....


; scrive 8 volte 255 in memoria a partire dalla   locazione di indirizzo 96 

         mov d,96 

         mov c,8
; completa ....
; completa ....
; completa ....
; completa ....


; scrive 8 volte 255 in memoria a partire dalla   locazione di indirizzo 112 

        mov d,112

        mov c,8
; completa ....
; completa ....
; completa ....
; completa ....

         hlt
